security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        bb:
            id: App\Security\UserProvider

    role_hierarchy:
        ROLE_ADMIN: ROLE_SUPER_MODERATOR
        ROLE_SUPER_MODERATOR: ROLE_MODERATOR
        ROLE_MODERATOR: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|images)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LegacyAuthenticator
            stateless: true
