security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        bb:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            id: App\Security\LegacyEncoder

    role_hierarchy:
        ROLE_ADMIN: ROLE_SUPER_MODERATOR
        ROLE_SUPER_MODERATOR: ROLE_MODERATOR
        ROLE_MODERATOR: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|images)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN] }
